#mongodb
spring:
       data:
           mongodb:
                 host: localHost
                 port: 27017
                 database: test

#logging
logging:
      level:
          org.springframework.data: debug
          level: error